# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./page/
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-artifact@v4  # Using the correct version
        with:
          name: jekyll-site-artifact  # This is the name of the uploaded artifact
          path: ./_site  # Path to the folder containing the built site

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build  # Ensures that the build job is completed before deployment
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4  # Using the correct version
        with:
          name: jekyll-site-artifact  # The name of the artifact uploaded in the build step
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          artifact_name: jekyll-site-artifact  # Correct artifact name to use during deployment
